# -*- coding: utf-8 -*-
"""2348409_Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13i_-vuZBzccldtLCgucfluWndjcvk6rf

**Lab 02- Data Exploration using Non-Parametric methods**

* *Created by: Angeline A*
* *Reg No: 2348409*

* Edited on: 21/02/2024
* Submitted on: 21/02/2024

* *numpy* is imported to perform mathematical operations
* *pandas* is impoted to perform data analysis and manipulation
* *matplotlib.pyplot* is imported to get a collection of command style functions that make matplotlib work like MATLAB
* *seaborn* is imported to help us in understanding the data with the help of plotting
* *plotly.express* is imported to visualize a variety of data
* scipy.stats is imported to help us in technical and scientific computing
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats

"""**2. Load the dataset into your runtime environment.**

In the below code, the dataset uploaded is read and stored
"""

df = pd.read_csv("/content/country_wise_latest.csv")
df

"""**3. Perform EDA and narrate the basic information about dataset.**

* In the below code, the shape of the dataset is envisioned.
* From the result of the below code, we can infer that the shape of the dataset is (187,15) which means it has 187 rows and 15 columns.
"""

df.shape

"""* In the below code, the size of the dataset is envisioned.
* From the result of the below code, we can infer that the total no of values/information present in the dataset is 2805.
"""

df.size

"""* In the below code, the columns that are there in the dataset is derived.
* From the result of the below code, we can infer that there are 15 columns with names,
 * 'Country/Region'
 * 'Confirmed'
 * 'Deaths'
 * 'Recovered'
 * 'Active'
 * 'New cases'
 * 'New deaths'
 * 'New Recovered'
 * 'Deaths / 100 Cases'
 * 'Recovered / 100 Cases'
 * 'Deaths / 100 Recovered'
 * 'Confirmed last week'
 * '1 week change'
 * '1 week % increase'
 * 'WHO Region'


"""

df.columns

"""* In the below code, the datatypes of each of the columns is derived.
* From the result of the below code, we can infer the datastypes of each of the columns which are mainly,
 * Object  - Anything that is assigned to the variable
 * int64 - 64 int integer
 * float64 - double precision float
"""

df.dtypes

"""In the below code,
The first ten rows are called with the help of the function ***head()*** which will helps us to get the first few rows of the dataset.
* It depends on the number that is given inside the brackets.
* By default, it will give us the 1st five rows of the dataset.
"""

df.head(10)

"""* In the below code, we are checking whether there are any null values present in the dataset.
* From the result of the below code, we can infer that there are no null values in the dataset.
"""

df.isnull().count()

"""* The below code gives the information about the dataset.
* The information like,
 * Column names
 * Count of Null and Non-Null values
 * Datatypes of all the columns
 * Memory usage
"""

df.info()

"""**4. UNIVARIATE ANALYSIS**
* *Numerical Variables*
  * a. Calculate basic descriptive statistics (mean, median, mode, standard deviation,
min, max, quartiles, etc.).

* In the below codee, we use the describe() function to get the descriptive statistics of the given dataframe.
* The result of the function includes information about numerical data and the information are,
 * count
 * mean
 * standard deviation
 * minimum value(min)
 * maximum value(max)
 * 25% - Lower Percentile
 * 50% - Median
 * 75% - Upper Percentile
"""

df.describe()

"""In the below code, we can infer that,
* df: This refers to a DataFrame object. DataFrames are a fundamental data structure in the Pandas library, which is used for data manipulation and analysis in Python.

* .groupby('WHO Region'): This is a method call on the DataFrame df. It groups the rows of the DataFrame based on the unique values in the 'WHO Region' column. After this operation, you essentially have separate groups of rows for each unique value in the 'WHO Region' column.

* ['New cases']: Once the DataFrame is grouped by 'WHO Region', this part of the code selects the column 'New cases' from each group. This means that for each group (each unique 'WHO Region'), it will focus on the data in the 'New cases' column.

* .describe(): After selecting the 'New cases' column for each group, this method computes summary statistics for that column within each group. These statistics include count (number of non-null values), mean (average), std (standard deviation), min (minimum value), 25th percentile, 50th percentile (median), 75th percentile, and max (maximum value).

* The entire expression df.groupby('WHO Region')['New cases'].describe() returns a DataFrame containing the summary statistics described above, with each row corresponding to a unique 'WHO Region' and each column corresponding to a summary statistic.
"""

print(df.groupby('WHO Region')['New cases'].describe())

"""**b. Visualize the distribution using histograms, kernel density plots, or box plots.**

In the below, we can infer that
* sns.histplot(): This function from Seaborn is used to create a histogram. It allows for visualizing the distribution of a dataset by dividing the data into bins and displaying bars for each bin. Optionally, it can also plot a kernel density estimation (KDE) curve over the histogram.
* df['Deaths']: This specifies the data that will be plotted in the histogram. It retrieves the 'Deaths' column from the DataFrame df, assuming df is previously defined.
* bins=10: This parameter determines the number of bins to use in the histogram. In this case, it's set to 10, meaning the data will be divided into 10 equally spaced intervals.
* kde=True: This parameter enables the kernel density estimation (KDE) plot. KDE is a non-parametric way to estimate the probability density function of a random variable, providing a smooth representation of the distribution.
* plt.show(): This function from Matplotlib displays the plot that has been created. It's necessary to call this function to actually render and display the visualization.
"""

#Histogram with kde
sns.histplot(df['Deaths'], bins=10, kde=True)
plt.show()

"""*Categorical variables*
 * a. Display frequency tables showing counts and percentages.

Ihe below code, we can infer that,
* frequency_table = df['WHO Region'].value_counts(): This line of code calculates the frequency of each unique value in the 'WHO Region' column of the DataFrame df. The value_counts() method returns a Series containing counts of unique values. Each unique value represents a region, and the count represents the frequency of occurrences of each region in the column.

* percentages = (frequency_table/len(df))*100: This line calculates the percentage of each region's frequency in the 'WHO Region' column. It divides each frequency in the frequency_table by the total number of rows in the DataFrame (len(df)), and then multiplies by 100 to convert the result to a percentage.

* result_df = pd.DataFrame({'Counts':frequency_table,'Percentage':percentages}): This line creates a new DataFrame called result_df containing two columns: 'Counts' and 'Percentage'. The 'Counts' column contains the frequency values from the frequency_table, while the 'Percentage' column contains the corresponding percentages calculated in the previous step.

* result_df: Finally, this line returns the resulting DataFrame result_df, which contains the frequency counts and percentages for each unique value in the 'WHO Region' column of the original DataFrame df. This DataFrame can be further analyzed or used for visualization.
"""

frequency_table = df['WHO Region'].value_counts()
percentages = (frequency_table/len(df))*100
result_df = pd.DataFrame({'Counts':frequency_table,'Percentage':percentages})
result_df

"""**b. Visualize using bar plots.**

In the below code, we can infer that
* cht1 = sns.countplot(data=df, x='WHO Region'): This line creates a count plot using Seaborn's countplot() function. It specifies the DataFrame (df) from which the data will be drawn and the variable ('WHO Region') to be plotted on the x-axis. This function essentially counts the occurrences of each unique value in the 'WHO Region' column and creates a bar plot to represent the counts.

* cht1.bar_label(cht1.containers[0]): This line adds labels to the bars in the count plot. cht1.containers[0] returns the bars in the plot, and bar_label() is used to add labels to these bars based on their heights (counts).

* plt.show(): Finally, this line displays the plot using Matplotlib's show() function.
"""

cht1 = sns.countplot(data = df, x ='WHO Region')
cht1.bar_label(cht1.containers[0])
plt.show()

"""**5. BIVARIATE ANALYSIS**
* **a. Explore relationships between pairs of numerical variables using scatter plots or pair plots.**

In the below code, we can infer that,
* df.plot(kind='scatter', x='Confirmed', y='Recovered', s=40, alpha=.8): This line generates a scatter plot using the Pandas DataFrame plot functionality. It specifies the kind of plot to be 'scatter' and sets the 'Confirmed' column as the x-axis variable and the 'Recovered' column as the y-axis variable. The s parameter adjusts the size of the markers in the plot, and alpha controls the transparency of the markers.

* plt.gca().spines[['top', 'right',]].set_visible(False): This line removes the top and right spines (borders) of the plot. plt.gca() gets the current Axes instance, and .spines[['top', 'right',]].set_visible(False) hides the spines on the top and right sides of the plot.
"""

# @title Confirmed vs Recovered

df.plot(kind='scatter', x='Confirmed', y='Recovered', s=40, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

"""**b. Explore relationships between numerical and categorical variables using box
plots or violin plots.**

In the below code, we can infer that,
* sns.boxplot(data=df, x=df['WHO Region'], y=df['New cases']): This line creates a box plot using Seaborn's boxplot() function. It specifies the DataFrame (df) from which the data will be drawn and sets the 'WHO Region' column as the categorical variable on the x-axis and the 'New cases' column as the numerical variable on the y-axis. The box plot visualizes the distribution of 'New cases' within each category of 'WHO Region'.

* plt.title("Box plot of Numerical Variabe by category"): This line sets the title of the plot to "Box plot of Numerical Variabe by category" using Matplotlib's title() function.

* plt.xlabel('WHO Region'): This line sets the label for the x-axis to "WHO Region" using Matplotlib's xlabel() function.

* plt.ylabel('New cases'): This line sets the label for the y-axis to "New cases" using Matplotlib's ylabel() function.

* plt.show(): Finally, this line displays the plot using Matplotlib's show() function.
"""

sns.boxplot(data = df, x = df['WHO Region'], y = df['New cases'])
plt.title("Box plot of Numerical Variabe by category")
plt.xlabel('WHO Region')
plt.ylabel('New cases')
plt.show()

"""**c. Calculate correlation coefficients between numerical variables.**

In the below code, we are seperating the numerical data from the dataset named df and storing it in the variable df1
"""

df1 = df[['Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases',
       'Recovered / 100 Cases', 'Deaths / 100 Recovered',
       'Confirmed last week', '1 week change' ]]
df1

"""In the below code, we see how the numerical data are related gto each other based on the correlation coefficient."""

df1.corr()

"""**6. NON-PARAMETRIC METHODS**

For our dataset, Mann-Whitney U test will be suitable, so we choose Mann-Whitney U test

In the below code, we are converting the dataset into a dataframe
"""

df = pd.DataFrame(df)

"""In the below code, we can infer that,
* Europe_newcases = df[df['WHO Region'] == 'Europe']['New cases']: This line filters the DataFrame df to only include the 'New cases' data for the 'Europe' region. It selects the 'New cases' column where the 'WHO Region' is 'Europe'.

* Africa_newcases = df[df['WHO Region'] == 'Africa']['New cases']: This line filters the DataFrame df to only include the 'New cases' data for the 'Africa' region. It selects the 'New cases' column where the 'WHO Region' is 'Africa'.

* mann_whitney_test = stats.mannwhitneyu(Europe_newcases, Africa_newcases): This line performs the Mann-Whitney U test using SciPy's mannwhitneyu() function. This non-parametric test is used to determine whether two independent samples have different distributions. It takes the two sets of data ('Europe_newcases' and 'Africa_newcases') as input and returns the test statistic and p-value.

* print("\nMann-Whitney U test result:"): This line prints a header indicating the start of the Mann-Whitney U test result.

* print("U Statistic: ", mann_whitney_test.statistic): This line prints the U statistic, which is the test statistic computed by the Mann-Whitney U test. It represents the degree of difference or similarity in the distributions of the two samples.

* print("p-value:", mann_whitney_test.pvalue): This line prints the p-value computed by the Mann-Whitney U test. The p-value indicates the probability of observing the given test statistic (or a more extreme value) under the null hypothesis that the distributions of the two samples are the same. A low p-value suggests that the null hypothesis should be rejected, indicating a significant difference between the distributions.
"""

Europe_newcases = df[df['WHO Region'] == 'Europe']['New cases']
Africa_newcases = df[df['WHO Region'] == 'Africa']['New cases']
mann_whitney_test = stats.mannwhitneyu(Europe_newcases,Africa_newcases)
print("\nMann-Whitney U test result:")
print("U Statistic: ", mann_whitney_test.statistic) #The degree of distribution between the variables/values(Europe_newcases,Africa_newcases)
print("p=value:",mann_whitney_test.pvalue)

"""The result of the above code says that,
* U Statistic (1688.5):
The U statistic is a rank-sum statistic calculated by the Mann-Whitney U test. It quantifies the degree of difference or similarity in the distributions of the two samples ('Europe_newcases' and 'Africa_newcases').
In this case, the U statistic is 1688.5. Higher values of U suggest greater differences in the distributions of the two samples.

* p-value (0.0244):The p-value is a measure of the strength of evidence against the null hypothesis. It indicates the probability of obtaining the observed results, or results more extreme, if the null hypothesis is true.
A low p-value suggests that the observed results are unlikely to occur under the null hypothesis, leading to rejection of the null hypothesis.
In this case, the p-value is approximately 0.0244, which is below conventional significance levels such as 0.05 or 0.01.

* Interpretation:Since the p-value (0.0244) is less than the significance level (e.g., 0.05), we reject the null hypothesis.
Therefore, we conclude that there is a statistically significant difference in the number of new cases between the 'Europe' and 'Africa' regions.

* In summary, the results of the Mann-Whitney U test provide evidence that the distributions of new cases differ significantly between the 'Europe' and 'Africa' regions.
"""