# -*- coding: utf-8 -*-
"""2348409_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkVAZNGXjNRV3_X8M8QIUcKC4tX_24f7

**Lab 01- Exploratory Data Analysis**

* *Created by: Angeline A*
* *Reg No: 2348409*

* Edited on: 15/02/2024

*In the below code, we are importing necessary python packages to perform the EDA process*

* *numpy* is imported to perform mathematical operations
* *pandas* is impoted to perform data analysis and manipulation
* *matplotlib.pyplot* is imported to get a collection of command style functions that make matplotlib work like MATLAB
* *seaborn* is imported to help us in understanding the data with the help of plotting
* *plotly.express* is imported to visualize a variety of data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats

"""In the below code, the dataset uploaded is read and stored"""

df = pd.read_csv("/content/Diabetes_prediction.csv")
df

"""* In the below code, the shape of the dataset is envisioned.
* From the result of the below code, we can infer that the shape of the dataset is (100000,11) which means it has 1 lakh rows and 11 columns.
"""

df.shape

"""* In the below code, the size of the dataset is envisioned.
* From the result of the below code, we can infer that the total no of values/information present in the dataset is 1100000.
"""

df.size

"""* In the below code, the columns that are there in the dataset is derived.
* From the result of the below code, we can infer that there are 11 columns with names,
 * 'employeeName'
 * 'Patient_id'
 * 'gender'
 * 'age'
 * 'hypertension'
 * 'heart_disease
 * 'smoking_history'
 * 'bmi'
 * 'HbA1c_level'
 * 'blood_glucose_level'
 * 'diabetes'

"""

df.columns

"""* In the below code, the datatypes of each of the columns is derived.
* From the result of the below code, we can infer the datastypes of each of the columns which are mainly,
 * Object  - Anything that is assigned to the variable
 * int64 - 64 int integer
 * float64 - double precision float
"""

df.dtypes

"""In the below code,
The first ten rows are called with the help of the function ***head()*** which will helps us to get the first few rows of the dataset.
* It depends on the number that is given inside the brackets.
* By default, it will give us the 1st five rows of the dataset.
"""

df.head(10)

"""* In the below code, we are checking whether there are any null values present in the dataset.
* From the result of the below code, we can infer that there are no null values in the dataset.
"""

df.isnull().count()

"""* The below code gives the information about the dataset.
* The information like,
 * Column names
 * Count of Null and Non-Null values
 * Datatypes of all the columns
 * Memory usage
"""

df.info()

"""* In the below codee, we use the describe() function to get the descriptive statistics of the given dataframe.
* The result of the function includes information about numerical data and the information are,
 * count
 * mean
 * standard deviation
 * minimum value(min)
 * maximum value(max)
 * 25% - Lower Percentile
 * 50% - Median
 * 75% - Upper Percentile
"""

df.describe()

"""* The below code is used to get the information about the descriptive statistics based on the gender.
  * df.groupby('gender'): This groups the DataFrame df by the values in the 'gender' column.
  * ['age']: This specifies that we are interested in the 'age' column of the grouped DataFrame.
  * .describe(): This method computes summary statistics for the grouped data. It calculates count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum values for each group.
"""

print(df.groupby('gender')['age'].describe())

"""In the below code, we converting the data to a dataframe with the help of the function pd.DataFrame()."""

df = pd.DataFrame(df)

"""* The below code does the test statistics between female and male based on their BMI.
  * male_hp = df[df['gender'] == 'Male']['hypertension']: This selects the Hypertension values from the DataFrame df where the gender is 'Male' and assigns them to the variable male_hp.

  * female_hp = df[df['gender'] == 'Female']['hypertension']: This selects the Hypertension values from the DataFrame df where the gender is 'Female' and assigns them to the variable female_hp.

  * t_statistic, p_value = stats.ttest_ind(male_hp, female_hp): This performs an independent two-sample t-test (ttest_ind) using the Hypertension values for males and females. It returns the t-statistic and the p-value.
"""

# Parametric tests - Example: t-test for comparing Hypertension between Male and Female populations
male_hp = df[df['gender'] == 'Male']['hypertension']
female_hp = df[df['gender'] == 'Female']['hypertension']

t_statistic, p_value = stats.ttest_ind(male_hp, female_hp)

print("\nT-test results for Hypertension between Male and Female populations:")
print("T-statistic:", t_statistic)
print("P-value:", p_value)

"""* In the above code, we are comaring whether the hypertension between male and female populations are equal or not which is the Null Hypothesis.
  * From the above code, we infer that the p-value = 5.428e-06 is less than the level of significance 0.05 which means that the **Null hypothesis is rejected**.
  * Hence, we can conclude that the Hypertension between the Male and Female Populations are not equal

* Data Selection:
  * female_bgl = df[df['gender'] == 'Female']['blood_glucose_level']: This line selects the blood glucose level data from the DataFrame df where the gender is 'Female' and stores it in the variable female_bgl.

* Normal Distribution Fitting:
 * mu, sigma = stats.norm.fit(female_bgl): This line fits a normal distribution to the data using the norm.fit function from scipy.stats.
 * It estimates the parameters of the normal distribution (mean and standard deviation) that best fit the data.
 * The variable mu represents the mean of the fitted distribution, and sigma represents the standard deviation.
"""

# Parametric modeling - Example: Fitting a normal distribution to female Blood Glucose Level
female_bgl = df[df['gender'] == 'Female']['blood_glucose_level']
mu, sigma = stats.norm.fit(female_bgl)
print("\nParameters of the fitted normal distribution for female Blood Glucose Level:")
print("Mean (mu):", mu)
print("Standard deviation (sigma):", sigma)

"""From the result code, we can infer that,
* Mean (mu): The mean of the fitted normal distribution is approximately 137.47. This represents the average blood glucose level for females in the dataset.

* Standard deviation (sigma): The standard deviation of the fitted normal distribution is approximately 40.10. This measures the spread or variability of blood glucose levels among females in the dataset. A higher standard deviation indicates more variability around the mean.

* These parameters provide insights into the central tendency and variability of blood glucose levels among females in the dataset.

The below code explains,
* Count Plot Creation:
 * cht1 = sns.countplot(data=df, x='diabetes'): This line creates a count plot using Seaborn's countplot function.
 * It specifies the DataFrame (data=df) and the column (x='diabetes') to plot.
* Adding Value Labels:
 * cht1.bar_label(cht1.containers[0]): This line adds labels to the bars of the count plot.
 * It uses the bar_label method of the count plot object (cht1) and passes the container of bars (cht1.containers[0]) to add labels to each bar.
* Plot Display:
 * plt.show(): This line displays the count plot.
"""

cht1 = sns.countplot(data = df, x ='diabetes')
cht1.bar_label(cht1.containers[0])
plt.show()

"""The below code explains,
* Data Selection:
 * male_bgl = df[df['gender'] == 'Male']['blood_glucose_level']: This line selects the blood glucose level data from the DataFrame df where the gender is 'Male' and stores it in the variable male_bgl.
* Q-Q Plot Generation:
 * stats.probplot(male_bgl, dist="norm", plot=plt): This line generates a Q-Q plot using the probplot function from scipy.stats.
 * It compares the quantiles of the male blood glucose level data (male_bgl) against the quantiles of a normal distribution (dist="norm").
 * The plot=plt parameter indicates that the plot should be displayed using the Matplotlib plt module.
* Plot Customization:
 * plt.title("Q-Q plot for Male Heights"): This line sets the title of the plot to "Q-Q plot for Male Heights".
* Plot Display:
 * plt.show(): This line displays the generated Q-Q plot.
"""

# Probability plots - Example: Q-Q plot for male Blood Glucose Level
print("\nProbability plot for male Blood Glucose Level:")
male_bgl = df[df['gender'] == 'Male']['blood_glucose_level']
stats.probplot(male_bgl, dist="norm", plot=plt)
plt.title("Q-Q plot for Male Blood Glucose Level")
plt.show()

"""The below code explains,
* Data Selection:
 * female_HbA1c = df[df['gender'] == 'Male']['HbA1c_level']: This line selects the HbA1c level data from the DataFrame df where the gender is 'Male' and stores it in the variable female_HbA1c.
 * It seems there's a mistake here where it says 'Male' but it's supposed to be 'Female' since we're referring to female HbA1c levels.
* Histogram Plot:
 * plt.hist(female_HbA1c, bins=5, density=True, alpha=0.6, color='g', label='Female HbA1c'): This line plots a histogram of the HbA1c levels for females.
 * Parameters like bins, density, alpha, color, and label control the appearance of the histogram.
* Fitted Normal Distribution Curve:
 * x = np.linspace(xmin, xmax, 100): This line creates a range of x-values for the normal distribution curve, spanning from xmin to xmax.
 * p = stats.norm.pdf(x, mu, sigma): This line calculates the probability density function (PDF) values for the fitted normal distribution using the mean (mu) and standard deviation (sigma) obtained earlier.
 * plt.plot(x, p, 'k', linewidth=2, label='Fitted Normal Distribution'): This line plots the fitted normal distribution curve on the histogram plot.
 * Parameters like 'k' for color, linewidth, and label control the appearance and labeling of the curve.
* Plot Customization:
 * plt.xlabel('Height'): This line sets the label for the x-axis.
 * plt.ylabel('Density'): This line sets the label for the y-axis.
 * plt.title('Histogram and Fitted Normal Distribution for Female HbA1c'): This line sets the title of the plot.
 * plt.legend(): This line adds a legend to the plot, incorporating labels specified earlier.
* Plot Display:
 * plt.show(): This line displays the histogram with the fitted normal distribution curve.
"""

# Plot histogram and fitted normal distribution
female_HbA1c = df[df['gender'] == 'Female']['HbA1c_level']
plt.hist(female_HbA1c, bins=5, density=True, alpha=0.6, color='g', label='Female HbA1c')
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, mu, sigma)
plt.plot(x, p, 'k', linewidth=2, label='Fitted Normal Distribution')
plt.xlabel('Height')
plt.ylabel('Density')
plt.title('Histogram and Fitted Normal Distribution for Female HbA1c')
plt.legend()
plt.show()

"""* The below code explains,
 * Histogram Plot Creation:
   * cht2 = sns.histplot(data=df, x='gender', kde=True, hue='smoking_history'): This line creates a histogram plot using Seaborn's histplot function.
   *  It specifies the DataFrame (data=df), the column to plot (x='gender'), and enables KDE estimation (kde=True). Additionally, it uses the 'smoking_history' column to differentiate the histograms by hue.
 * Plot Display:
   * plt.show(): This line displays the histogram plot created using Seaborn.
"""

cht2 = sns.histplot(data = df, x = 'gender', kde = True, hue = 'smoking_history')
plt.show()

"""The below code explains,
* Data Preparation:
 * labels = df['diabetes'].value_counts().index: This line extracts the unique values in the 'diabetes' column and stores them as labels.
 * values = df['diabetes'].value_counts(): This line calculates the count of each unique value in the 'diabetes' column and stores them as values.
* Pie Chart Creation:
 * plt.pie(x=values, labels=labels, autopct='%1.1f%%', shadow=True): This line creates a pie chart using Matplotlib's pie function. It takes the values (x=values) and labels (labels=labels) as input.
 * The autopct='%1.1f%%' parameter formats the percentage values displayed on the chart with one decimal point.
 * The shadow=True parameter adds a shadow effect to the pie chart slices.
* Plot Display:
 * plt.show(): This line displays the pie chart.
"""

labels = df['diabetes'].value_counts().index
values = df['diabetes'].value_counts()
plt.pie(x=values,labels=labels,autopct = '%1.1f%%',shadow=True)
plt.show()